FORMAT: 1A
HOST: http://uat.fxhello.com/api/

# FX Hello

Polls is a simple API allowing consumers to view polls and vote in them.

IMPORTANT: The API URL is set to UAT server in this documentation. Make sure to change the URL to http://app.fxhello.com to communicate with the Production system.

## Authentication [/authenticate]

### Login [POST]
Allows the user to login using their email address and the password. The API will return a JSON Web Token (JWT) upon successful login. This token needs to be sent in the header of each call of the API.

+ Request

    + Headers
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "email": "user@example.com",
            "password": "Abc@1234"
        }
    
+ Response 200 (application/json)

    + Body
        {
            "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1",
            "isError": false
        }

### Register [POST /register]
Allows user to create an account

+ Request (application/json)

    + Headers
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "name": "John",
            "email": "john@example.com",
            "password": "Abc@1234",
            "password_confirmation": "Abc@1234"
        }

+ Response 200 (application/json)

    + Body
        {
            "user": {
                "name": "TOne",
                "email": "tone@flatorb.com",
                "updated_at": "2016-11-21 05:56:03",
                "created_at": "2016-11-21 05:56:03",
                "id": 1640,
                "tax_rate": 0
            }
            "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1",
            "isError": false
        }

### Create Organization [POST /organizationCreate]
User can create a new organization. The new organization will become the new active organization of the user.

+ Parameters
    + orgName (required) ... This is the name of the organization

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "orgName": "Widget Corp"
        }

+ Response 200 (application/json)

    + Body
        {
            "orgId": 1624,
            "message": "Organization created successfully",
            "isError": false
        }

### Get Settings [GET /settings]
This will return all the settings associated for the user, user's current organization, etc.

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
        {
            "sendHealthChecks": true,
            "healthCheckFrequency": 15,
            "orgSettings": {
                "modules": {
                    "crm": true,
                    "support": true,
                    "marketing": true,
                    "sales": true,
                    "salesForce": true,
                    "finance": true,
                    "purchasing": true,
                    "products": true,
                    "inventory": true,
                    "warehouse": true,
                    "distributionCenters": true,
                    "productionManagement": true,
                    "gamification": true,
                    "fleetManagement": true,
                    "distribution": true,
                    "assetManagement": true,
                    "workflow": true,
                    "hr": true,
                    "projectManagement": true,
                    "lms": true,
                    "deviceCloud": true
                },
                "useTax": false
            },
            "userSettings": "",
            "isError": false
        }

## Categories [/categories]

### Get a list of categories [POST /categories]
Allows the user to get a list of categories and their ID's that belongs to the Organization/team. 

+ Parameters
    + subType (optional, number) ... NULL or 0 return all categories. Passing the relavent subType return only the applicable categories. (subType = 3 for customers, subType = 4 for contacts, subType = 5 for products, subType = 17 for marketing resources and subType = 32 for marketing campaign)

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "subType": 0
        }

+ Response 200 (application/json)

    + Body
        {
          "payload": {
              "0": {
                "id": "57fdc2006b0bdc7d6809b522",
                "name": "New contact category",
                "subType": 4
              },
          }
        }
      

### Create category [POST /categoryCreate]
This allows the user to create a new category for the specified subType.

+ Parameters
    + subType (optional, number) ...  subType = 3 for customers, subType = 4 for contacts, subType = 17 for marketing resources and subType = 32 for marketing campaign. Can keep it as NULL or 0.
    + category_name (string)


+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "name": "The new contact category name"
            "subType": 3
        }

+ Response 200 (application/json)

    + Body
        {
          "message": "Data saved successfully!!!"
        }

## Background services [/services]


## Stores [/stores]

### Get list of stores [POST /stores]
Get a list of stores (warehouses, store locations, etc.) along with their ID, type.

+ Parameters
    + subType (optional, number) ... NULL or 0 return all stores. Passing the relavent subType return only the applicable stores from the store type.
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "subType": 0
        }

+ Response 200 (application/json)

    + Body
        {
           "payload": [
                {
                  "id": "5834226c6b0bdc4b0d33ef92",
                  "storeName": "Demo warehouse"
                 }
            ]
        }

### Create a Store [POST /stores/storeCreate]
This allows the user to create a new store for the specified type.

+ Parameters
    + name (string) 
    + location (string)
    + telephone1 (string)
    + telephone2 (optional, string)
    + fax (optional, string)
    + email (optional, string)
    + country (number)
    + description (optional, string)
    + address1 (optional, string)
    + address2 (optional, string)
    + state (optional, string)
    + zip (optional, string)
    + city (optional, string)


+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "name": "Demo warehouse"
            "location": "New York"
            "telephone1": "011 11111111"
            "telephone2": "022 22222222"
            "fax": "033 33333333"
            "email": "demo@flatorb.com"
            "country": 232
            "description": "Demo description"
            "address1": "123 Main Street"
            "address2": "Unit 8"
            "state": "NY"
            "zip": "232"
            "city": "United States"
        }

+ Response 200 (application/json)

    + Body
       {
          "message": "Data saved successfully!!!",
          "store_id": "5834226c6b0bdc4b0d33ef92"
        }

## Stock [/stock]

### Audit using RFID data [POST /stock/auditRFIDData]
An defined store can be audied using the RFID data. The RFID data will be matched against the defined store and will return data.

+ Parameters
    + storeId (required, string) ... The ID of the store to be audited
    + rfidTags (required, string) ... Json string array of RFID tags with their TID and EPC
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "storeId": "18392ac163a",
            "rfidTags": {
                {
                    "tid": "4654323165465FABCE33",
                    "epc": "4564E536D8FES"
                },
                {
                    "tid": "4654323165465FABCE33",
                    "epc": "4564E536D8FES"
                },
                {
                    "tid": "4654323165465FABCE33",
                    "epc": "4564E536D8FES"
                }
            }
        }

+ Response 200 (application/json)

    + Body
        {
           "payload": [
                {
                    "id": "1b897f23ab",
                    "timestamp": "2016-11-20 16:08:32",
                    "performedBy": "John",
                    "storeId": "5834226c6b0bdc4b0d33ef92",
                    "storeName": "Demo warehouse",
                    "qtyOnBook": 1300,
                    "qtyTallying": 1450,
                    "qtyMissing": 75,
                    "qtyExcess": 25,
                    "missing": [
                        {
                            "pid": "1793bc23fa33",
                            "name": "Product name",
                            "image": "http://www.example.com/img/sample.jpg"
                        },
                        {
                            "pid": "1793bc23fa33",
                            "name": "Product name",
                            "image": "http://www.example.com/img/sample.jpg"
                        },
                        {
                            "pid": "1793bc23fa33",
                            "name": "Product name",
                            "image": "http://www.example.com/img/sample.jpg"
                        }
                    ],
                    "excess": [
                        {
                            "pid": "1793bc23fa33",
                            "name": "Product name",
                            "image": "http://www.example.com/img/sample.jpg"
                        },
                        {
                            "pid": "1793bc23fa33",
                            "name": "Product name",
                            "image": "http://www.example.com/img/sample.jpg"
                        },
                        {
                            "pid": "1793bc23fa33",
                            "name": "Product name",
                            "image": "http://www.example.com/img/sample.jpg"
                        }
                    ],
                    "tallying": [
                        {
                            "pid": "1793bc23fa33",
                            "name": "Product name",
                            "image": "http://www.example.com/img/sample.jpg"
                        },
                        {
                            "pid": "1793bc23fa33",
                            "name": "Product name",
                            "image": "http://www.example.com/img/sample.jpg"
                        },
                        {
                            "pid": "1793bc23fa33",
                            "name": "Product name",
                            "image": "http://www.example.com/img/sample.jpg"
                        }
                    ]
                }
            ]
        }

## CRM [/crm]

### Get a list of customers [POST /crm/customers]
Allows the user to get a list of customers and their information that belongs to the Organization/team. 
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
        {
           "payload": [
                {
                  "id": "57ff51896b0bdc0747634a73",
                  "name": "Francisca Industries PVT LTD",
                  "status": "Prospect",
                  "email": "fransis@flatorb.com",
                  "telephone": "675677 , 234",
                  "added_by": "Keshani",
                  "profileimage": "https://cdn.fxhello.com/img/imgph300.png",
                  "profileImgStatus": false,
                  "created_on": "2016-10-13 09:19:03"
                 }
            ]
        }

### Display customer profile [POST /crm/customers/customer]
Allows the user to get customer details of the selected customer that belongs to the Organization/team. 

+ Parameters
    + customerid (string) ... Passing the relavent customerId to return only the relevant customer details.
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "customerid": 5806d9fe6b0bdc0209217585
        }

+ Response 200 (application/json)

    + Body
        {
          "payload": [
            {
              "id": "5806d9fe6b0bdc0209217585",
              "name": "Aileen Annie",
              "addresses": {
                "address1": "123 Main Street",
                "address2": "Unit 8",
                "city": "New York",
                "state": "New York",
                "stateid": "NY",
                "zip": "10601",
                "country": "United States",
                "countryid": "232",
                "description": "",
                "status": 1,
                "cuid": 6,
                "uuid": 6,
                "created_at": "2016-10-19 02:27:07",
                "updated_at": "2016-10-19 02:27:07"
              },
              "telephone1": "",
              "telephone2": null,
              "mobile": "",
              "fax": null,
              "status": "Prospect",
              "email": "",
              "website": "",
              "description": "",
              "profileimage": "https://cdn.fxhello.com/img/imgph300.png",
              "profileImgStatus": false,
              "leadSource": "Lead",
              "customerSince": "2016-10-19",
              "creditPeriod": null,
              "cuName": "Keshani",
              "created_at": "2016-10-19 02:27:07",
              "uuName": "Keshani",
              "updated_at": "2016-10-19 02:27:07"
            }
          ]
        }


### Create a customer [POST /crm/customers/customerCreate]
Allows the user to  saves a customer under the active Organization/team. 

+ Parameters
    + name (string) 
    + prefix (string)
    + category (optional, string)
    + email (optional, string)
    + website (optional, string)
    + country (number)
    + address1 (optional, string)
    + address2 (optional, string)
    + city (optional, string)
    + zip (optional, string)
    + state (optional, string)
    + telephone1 (optional, string)
    + telephone2 (optional, string)
    + mobile (string)
    + fax (optional, string)
    + status (int)
    + leadsource (string)
    + customer_since (optional, string)
    + description (optional, string)
    + designation (optional, string)
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "name": "Github test customer"
            "prefix": "Mr.""
            "category": "5801b8184189dc69ad4409e7"
            "email": "git@flatorb.com"
            "website": "www.github.com"
            "country": 232
            "address1": "123 Main Street"
            "address2": "Unit 8"
            "city": "New York"
            "zip": "10601"
            "state": "NY"
            "telephone1": "011 11111111"
            "telephone2": "022 22222222"
            "mobile": "077 7777777"
            "fax": "011 1111111"
            "status": 3
            "leadsource": "581ab6a058e13f4536380912"
            "customer_since": "2016-11-13"
            "description": "Test Customer"
            "designation": "Developer"
        }

+ Response 200 (application/json)

    + Body
        {
          "message": "Data saved successfully!!!",
          "customer_id": "583285a06b0bdc28804587c2"
        }


### Edit customer [POST /crm/customers/customerEdit]
Allows the user to get customer details of the selected customer to the edit form, that belongs to the Organization/team. 

+ Parameters
    + customerid (string) ... Passing the relavent customerId to return only the relevant customer details.
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "customerid": "583285a06b0bdc28804587c2"
        }

+ Response 200 (application/json)

    + Body
        {
          "payload": [
            {
              "id": "583285a06b0bdc28804587c2",
              "name": "Github test customer",
              "addresses": {
                "address1": "123 Main Street",
                "address2": "Unit 8",
                "city": "New York",
                "state": "New York",
                "stateid": "NY",
                "zip": "10601",
                "country": "United States",
                "countryid": "232",
                "description": "",
                "status": 1,
                "cuid": 1679,
                "uuid": 1679,
                "created_at": "2016-11-21 05:26:51",
                "updated_at": "2016-11-21 05:26:51"
              },
              "telephone1": "45345",
              "telephone2": "435345",
              "mobile": "34534",
              "fax": "345345",
              "statusID": "3",
              "status": "Lead",
              "email": "git@flatorb.com",
              "website": "",
              "description": "",
              "countryID": "232",
              "leadSourceID": "581ab6a058e13f4536380912",
              "leadSource": "Mailed",
              "customerSince": "1970-01-01",
              "cuName": "Keshani",
              "created_at": "2016-11-21 05:26:51",
              "uuName": "Keshani",
              "updated_at": "2016-11-21 05:26:51"
            }
          ]
        }


### Update customer [POST /crm/customers/customerUpdate]
Allows the user to  update the selected customer under the active Organization/team. 

+ Parameters
    + customerid (string) 
    + name (string) 
    + prefix (string)
    + category (optional, string)
    + email (optional, string)
    + website (optional, string)
    + country (number)
    + address1 (optional, string)
    + address2 (optional, string)
    + city (optional, string)
    + zip (optional, string)
    + state (optional, string)
    + telephone1 (optional, string)
    + telephone2 (optional, string)
    + mobile (string)
    + fax (optional, string)
    + status (int)
    + leadsource (string)
    + customer_since (optional, string)
    + description (optional, string)
    + designation (optional, string)
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "customerid": "583285a06b0bdc28804587c2"
            "name": "Github demo customer "
            "prefix": "Mr.""
            "category": "5801b8184189dc69ad4409e7"
            "email": "git@flatorb.com"
            "website": "www.github.com"
            "country": 232
            "address1": "123 Main Street"
            "address2": "Unit 8"
            "city": "New York"
            "zip": "10601"
            "state": "NY"
            "telephone1": "011 11111111"
            "telephone2": "022 22222222"
            "mobile": "077 7777777"
            "fax": "011 1111111"
            "status": 3
            "leadsource": "581ab6a058e13f4536380912"
            "customer_since": "2016-11-13"
            "description": "Test Customer"
            "designation": "Developer"
        }

+ Response 200 (application/json)

    + Body
        {
          "message": "Data updated successfully!!!",
          "code": 200
        }


### Get a list of contacts [POST /crm/contacts]
Allows the user to get a list of contacts and their information that belongs to the Organization/team. 
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
        {
           "payload": [
                {
                    "id": "57ff61a96b0bdc091d013592",
                    "name": "Genevieve Isabelle",
                    "company": null,
                    "position": "HR",
                    "telephone": "344234 , 234234",
                    "email": "gene@flatorb.com",
                    "added_by": "Keshani",
                    "profileimage": "https://cdn.fxhello.com/img/imgph300.png",
                    "profileImgStatus": false,
                    "created_on": "2016-10-13 10:27:52"
                }
                ]
        }


### Display contact profile [POST /crm/contacts/contact]
Allows the user to get contact details of the selected contact that belongs to the Organization/team. 

+ Parameters
    + contactid (string) ... Passing the relavent contactId to return only the relevant contact details.
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "contactid": 5806d9fe6b0bdc0209217585
        }

+ Response 200 (application/json)

    + Body
        {
          "payload": [
            {
              "id": "57ff61a96b0bdc091d013592",
              "customerName": null,
              "firstName": "Genevieve",
              "lastName": "Isabelle",
              "telephone": "344234",
              "mobile": "234234",
              "email": "gene@flatorb.com",
              "image": "",
              "position": "HR",
              "profileimage": "https://cdn.fxhello.com/img/imgph300.png",
              "profileImgStatus": false,
              "addresses": {
                "address1": "234 Main Steet",
                "address2": "Unit 8",
                "city": "New York",
                "state": "New York",
                "stateid": "NY",
                "zip": "10601",
                "country": "United States",
                "countryid": "232",
                "description": "",
                "status": 1,
                "cuid": 6,
                "uuid": 6,
                "created_at": "2016-10-13 10:27:52",
                "updated_at": "2016-10-13 10:27:52"
              }
            }
        ]
    }


### Create a contact [POST /crm/contacts/contactCreate]
Allows the user to  saves a contact under the active Organization/team. 

+ Parameters
    + customer (optional, string) 
    + prefix (string)
    + firstName (string)
    + middleName (optional, string)
    + lastName (optional, string)
    + email (optional, string)
    + country (number)
    + position (optional, string)
    + department (optional, string)
    + contact_type (optional, string)
    + telephone (optional, string)
    + mobile (string)
    + address1 (optional, string)
    + address2 (optional, string)
    + city (optional, string)
    + post_code (string)
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "customer": "583285a06b0bdc28804587c2"
            "prefix": "Mr.""
            "firstName": "Git"
            "middleName": "Contact"
            "lastName": "Demo"
            "email": "git@flatorb.com"
            "country": "232"
            "position": "Trainee Developer"
            "department": "IT"
            "contact_type": ""
            "telephone": "011 1111111"
            "mobile": "077 7777777"
            "address1": "123 Main Street"
            "address2": "Unit 8"
            "city": "New York"
            "post_code": "10601"
        }

+ Response 200 (application/json)

    + Body
    {
        "message": "Data saved successfully!!!",
        "contact_id": "58329bf16b0bdc244f367da3"
    }


### Edit contact [POST /crm/contacts/contactEdit]
Allows the user to get contact details of the selected contact to the edit form, that belongs to the Organization/team. 

+ Parameters
    + contactid (string) ... Passing the relavent contactId to return only the relevant contact details.
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "contactid": "58329bf16b0bdc244f367da3"
        }

+ Response 200 (application/json)

    + Body
        {
          "payload": [
            {
              "id": "58329bf16b0bdc244f367da3",
              "cutomerName": "Github demo customer ",
              "firstName": "Git",
              "middleName": "Contact",
              "lastName": "Demo",
              "telephone": "011 1111111",
              "mobile": "077 7777777",
              "email": "git@flatorb.com",
              "title": "Trainee Developer",
              "image": "",
              "department": "IT",
              "contact_type": "",
              "addresses": {
                "address1": "123 Main Street",
                "address2": "Unit 8",
                "city": "New York",
                "state": "New York",
                "zip": "10601",
                "country": "United States",
                "countryid": "232",
                "description": "",
                "status": 1,
                "cuid": 1679,
                "uuid": 1679,
                "created_at": "2016-11-21 07:02:07",
                "updated_at": "2016-11-21 07:02:07"
              }
            }
          ]
        }


### Update contact [POST /crm/contacts/contactUpdate]
Allows the user to  update the selected contact under the active Organization/team. 

+ Parameters
    + contactid (string) 
    + prefix (string) 
    + firstName (string)
    + middleName (optional, string)
    + lastName (optional, string)
    + email (optional, string)
    + country (number)
    + position (optional, string)
    + department (optional, string)
    + contact_type (optional, string)
    + telephone (optional, string)
    + mobile (string)
    + address1 (optional, string)
    + address2 (optional, string)
    + city (optional, string)
    + post_code (optional, string)
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "contactid": "583285a06b0bdc28804587c2"
            "prefix": "Github demo customer "
            "firstName": "Mr.""
            "middleName": "5801b8184189dc69ad4409e7"
            "lastName": "git@flatorb.com"
            "email": "www.github.com"
            "country": 23
            "position": "123"
            "department": "Galle Road"
            "contact_type": "Colombo"
            "telephone": "0"
            "mobile": "0"
            "address1": "011 11111111"
            "address2": "022 22222222"
            "city": "077 7777777"
            "post_code": "011 1111111"
        }

+ Response 200 (application/json)

    + Body
        {
          "message": "Data updated successfully!!!"
        }


### Get values for the customer create from dropdowns [POST /crm/customer/dropdowns]
Allows the user to get a list of values for the drop downs countries, customer status and lead source that belongs to the Organization/team. 

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
        {
          "payload": {
                "countries": [
                  {
                    "id": 3,
                    "country": "Afghanistan"
                  }
                ],
                "customerStatuses": [
                  {
                    "id": 1,
                    "status": "Customer"
                  },
                ],
                "leadSources": [
                  {
                    "id": "57fcd93e4189dc6a846be182",
                    "source": "This is test"
                  },
                ],
                "categories": [
                 {
                    "id": "57fdc2c06b0bdc7ee01a59d2",
                    "name": "New Customer category"
                  },
                ]
            }
        }


### Get values for the contact create from dropdowns [POST /crm/contact/dropdowns]
Allows the user to get a list of values for the drop downs countries and customers that belongs to the Organization/team. 

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
        {
          "payload": {
                "countries": [
                  {
                    "id": 3,
                    "country": "Afghanistan"
                  }
                ],
                "customers": [
                  {
                    "id": "57ff51896b0bdc0747634a73",
                    "name": "Francisca Industries PVT LTD"
                  },
                ]
            }
        }


## Support [/support]

### Get a list of supoort tickets [POST /support/tickets]
Allows the user to get a list of support tickets and their information that belongs to the Organization/team. 
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
        {
          "payload": [
              {
                "id": "58084d976b0bdc04741a55a2",
                "subject": "Test cases",
                "priority": "",
                "customer": "Toy Pvt Ltd",
                "last_modified": "2016-10-20 04:52:38",
                "assignees": "Nickles"
              }
            ]
        }

### Display support ticket profile [POST /support/tickets/ticket]
Allows the user to get support ticket details of the selected support ticket that belongs to the Organization/team. 

+ Parameters
    + ticketid (string) ... Passing the relavent ticketId to return only the relevant support ticket details.
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "ticketid": 582d2e9a6b0bdc020972fc62
        }

+ Response 200 (application/json)

    + Body
        {
          "payload": [
            {
              "id": "582d2e9a6b0bdc020972fc62",
              "customerName": "Connie Industries",
              "subject": "Demo 11/17",
              "description": "",
              "priorityName": "High",
              "assigneeName": "Nickles",
              "cuName": "Keshani",
              "created_at": "2016-11-17 04:14:06"
            }
          ]
        }


### Create a support ticket [POST /support/tickets/ticketCreate]
Allows the user to  saves a support ticket under the active Organization/team. 

+ Parameters
    + customer (string) 
    + contact_name (optional, string)
    + reported_date (optional, string)
    + due_date (optional, string)
    + assign_to (string)
    + priorityName (string)
    + subject (string)
    + description (optional, string)
    + time_estimate (optional, string)
    + billing_rate (optional, string)
    + total_cap (optional, string)
    + currency (optional, string)
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "customer": "581bf7296b0bdc0206307312"
            "contact_name": "Sam""
            "reported_date": "2016-11-22"
            "due_date": "2016-11-22"
            "assign_to": "5821771c6b0bdc037a1be432"
            "priorityName": "High"
            "subject": "Create Ticket"
            "description": "Test the ticket"
            "time_estimate": ""
            "billing_rate": ""
            "total_cap": ""
            "currency": ""
        }

+ Response 200 (application/json)

    + Body
        {
          "message": "Data saved successfully!!!",
          "ticket_id": "5833fe7f6b0bdc03d0103b52"
        }


### Get vales to the supoort ticket create form dropdowns [POST /support/tickets/dropdowns]
Allows the user to get a list of customers, currency and assignees that belongs to the Organization/team.

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
       {
        "payload": {
          "customers": [
              {
                "id": "57ff51896b0bdc0747634a73",
                "name": "Francisca Industries PVT LTD"
              }
            ],
          "assignees": [
            {
              "id": "5805a3536b0bdc039843aff2",
              "name": "Nickles Domnick"
            }
          ],
          "currency": [
            {
              "id": 3,
              "country": "Afghanistan",
              "currency": "AFN"
            }
          ]
        }
      }



## HR [/hr]

### Get a list of departments [POST /hr/departments]
Allows the user to get a list of departments and their ID's that belongs to the Organization/team. 

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
       {
          "payload": [
            {
              "id": "5801b8184189dc69ad440a11",
              "name": "Legal"
            }
          ]
        }


### Create a department [POST /hr/departmentCreate]
Allows the user to  saves a department under the active Organization/team. 

+ Parameters
    + dep_name (string) 
    + parent (optional, string)
    + description (optional, string)
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "dep_name": "Demo department"
            "parent": ""
            "description": "Testing"
        }

+ Response 200 (application/json)

    + Body
        {
          "message": "Data saved successfully!!!"
        }


### Edit a department [POST /hr/departmentEdit]
Allows the user to edit the details of the selected department under the active Organization/team. 

+ Parameters
    + dep_id (string) 
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "dep_id": "5832ac4d6b0bdc2882135a32"
        }

+ Response 200 (application/json)

    + Body
        {
          "payload": [
            {
              "id": "5832ac4d6b0bdc2882135a32",
              "name": "Demo department"
            }
          ]
        }


### Update department [POST /hr/departmentUpdate]
Allows the user to update the details of the selected department under the active Organization/team. 

+ Parameters
    + dep_id (string) 
    + dep_name (string) 
    + parent (optional, string) 
    + description (optional, string) 
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "dep_id": "5832ac4d6b0bdc2882135a32"
        }

+ Response 200 (application/json)

    + Body
        {
          "message": "Data updated successfully!!!"
        }


### Get a list of employment types [POST /hr/employee-types]
Allows the user to get a list of employment types and their ID's that belongs to the Organization/team. 

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
    {
        "payload": [
            {
              "id": "5801b8184189dc69ad4409d2",
              "name": "Internship"
            }
        ]
    }  


### Create employment type [POST /hr/employee-typeCreate]
Allows the user to create an employment type under to the Organization/team. 

+ Parameters
    + emp_type (string) 
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "emp_type": "Part time"
        }

+ Response 200 (application/json)

    + Body
        {
          "message": "Data saved successfully!!!"
        }


### Get a list of employees [POST /hr/employees]
Allows the user to get a list of employees and their information that belongs to the Organization/team. 
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
        {
          "payload": [
                {
                  "id": "5805a3536b0bdc039843aff2",
                  "name": "Nickles Domnick",
                  "contact": "23423412312 , 23423",
                  "email": "chamal@flatorb.com",
                  "title": "IT",
                  "department": "Finance"
                }
            ]
        }


### Display employee profile [POST /hr/employees/employee]
Allows the user to get employee details of the selected employee that belongs to the Organization/team. 

+ Parameters
    + employeeid (string) ... Passing the relavent empId to return only the relevant empId details.
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "employeeid": 5806d9fe6b0bdc0209217585
        }

+ Response 200 (application/json)

    + Body
        {
          "payload": [
            {
              "id": "581fef8c6b0bdc02094d57a2",
              "name": "Sam Doe",
              "addresses": {
                "address1": "123 Main Street",
                "address2": "Unit 8",
                "city": "New York",
                "state": "New York",
                "stateID": "NY",
                "zip": "10601",
                "country": "United States",
                "countryID": "232",
                "description": "",
                "status": 1,
                "cuid": 6,
                "uuid": 6,
                "created_at": "2016-11-07 03:05:46",
                "updated_at": "2016-11-07 03:05:46"
              },
              "telephone1": "",
              "telephone2": "",
              "mobile": "",
              "depName": "Postman",
              "description": "",
              "email": "sam@flatorb.com",
              "jobtitle": "Developer",
              "profileimage": "https://cdn.fxhello.com/img/imgph300.png",
              "profileImgStatus": false,
              "created_at": "2016-11-07 03:05:46",
              "updated_at": "2016-11-07 03:05:46"
            }
          ]
        }


### Create an employee [POST /hr/employees/employeeCreate]
Allows the user to  saves an employee under the active Organization/team. 

+ Parameters
    + emp_id (string) 
    + file_no (optional, string)
    + email (string)
    + country (number)
    + prefix (string)
    + firstname (string)
    + middlename (optional, number)
    + lastname (string)
    + address1 (optional, string)
    + address2 (optional, string)
    + city (optional, string)
    + zip (optional, string)
    + state (optional, string)
    + telephone1 (optional, string)
    + telephone2 (optional, string)
    + mobile (string)
    + nationality (optional, string)
    + ssn (optional, string)
    + birth_place (optional, string)
    + marital_status (optional, string)
    + religion (optional, string)
    + gender (optional, string)
    + immigration_status (optional, string)
    + description (optional, string)
    + emp_description (optional, string)
    + emp_type (string)
    + department (string)
    + job_title (string)
    + join_date (optional, string)
    + termination_date (optional, string)
    + birth_date (optional, string)
    + user (optional, string)
    + password (optional, string)
    + confirm_password (optional, string)
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "emp_id": "423423123"
            "file_no": "FX0092"
            "email": "git@flatorb.com"
            "country": 232
            "prefix": "Mr."
            "firstname": "Demo"
            "middlename": ""
            "lastname": "Sam"
            "address1": "123 Main Street"
            "address2": "Unit 8"
            "city": "New York"
            "zip": "10601"
            "state": "New York"
            "telephone1": "011 1111111"
            "telephone2": "022 2222222"
            "mobile": "077 7777777"
            "nationality": '"
            "ssn": '"
            "birth_place": '"
            "marital_status": '"
            "religion": '"
            "gender": "Male"
            "immigration_status": '"
            "description": '"
            "emp_description": '"
            "emp_type": "581c346d6b0bdc020671e1c2"
            "department": "581c28b16b0bdc02047fcaa3"
            "job_title": "Developer"
            "join_date": '"
            "termination_date": '"
            "birth_date": '"
            "user": '"
            "password": '"
            "confirm_password": '"
        }

+ Response 200 (application/json)

    + Body
    {
      "message": "Data saved successfully!!!",
      "employee_id": "5832bb016b0bdc05cf54b892"
    }


### Edit employee [POST /hr/employees/employeeEdit]
Allows the user to get employee details of the selected employee to the edit form, that belongs to the Organization/team. 

+ Parameters
    + employeeid (string) ... Passing the relavent employeeId to return only the relevant employee details.
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "employeeid": "5832bb016b0bdc05cf54b892"
        }

+ Response 200 (application/json)

    + Body
        {
          "payload": [
            {
              "id": "5832bb016b0bdc05cf54b892",
              "firstname": "Demo",
              "middlename": "",
              "lastname": "Sam",
              "addresses": {
                "main": {
                  "address1": "123 Main Street",
                  "address2": "Unit 8",
                  "city": "New York",
                  "state": "New York",
                  "stateID": "NY",
                  "zip": "10601",
                  "country": "United States",
                  "countryID": "232",
                  "description": "",
                  "status": 1,
                  "cuid": 1679,
                  "uuid": 1679,
                  "created_at": "2016-11-21 09:14:39",
                  "updated_at": "2016-11-21 09:14:39"
                }
              },
              "meta": {
                "nationality": "",
                "ssn": "",
                "birthPlace": "",
                "materialStatus": "",
                "religion": "",
                "gender": "Male",
                "immigrationStatus": "",
                "description": "",
                "telephone2": "022 2222222"
              },
              "telephone1": "011 1111111",
              "mobile": "077 7777777",
              "status": 1,
              "email": "git@flatorb.com",
              "description": "",
              "countryID": "Bouvet Island",
              "created_at": "2016-11-21 09:14:39",
              "updated_at": "2016-11-21 09:14:39"
            }
          ]
        }


### Update employee [POST /hr/employees/employeeUpdate]
Allows the user to  update the selected employee under the active Organization/team. 

+ Parameters
    + employeeid (string) 
    + emp_id (string) 
    + file_no (optional, string)
    + email (string)
    + country (number)
    + prefix (string)
    + firstname (string)
    + middlename (optional, number)
    + lastname (string)
    + address1 (optional, string)
    + address2 (optional, string)
    + city (optional, string)
    + zip (optional, string)
    + state (optional, string)
    + telephone1 (optional, string)
    + telephone2 (optional, string)
    + mobile (string)
    + nationality (optional, string)
    + ssn (optional, string)
    + birth_place (optional, string)
    + marital_status (optional, string)
    + religion (optional, string)
    + gender (optional, string)
    + immigration_status (optional, string)
    + description (optional, string)
    + emp_description (optional, string)
    + emp_type (string)
    + department (string)
    + job_title (string)
    + join_date (optional, string)
    + termination_date (optional, string)
    + birth_date (optional, string)
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "employeeid": "5832bb016b0bdc05cf54b892"
            "emp_id": "423423123"
            "file_no": "FX0092"
            "email": "git@flatorb.com"
            "country": 34
            "prefix": "Mr."
            "firstname": "Testing"
            "middlename": ""
            "lastname": "Sam"
            "address1": "123 Main Street"
            "address2": "Unit 8"
            "city": "New York"
            "zip": "10601"
            "state": "New York"
            "telephone1": "011 1111111"
            "telephone2": "022 2222222"
            "mobile": "077 7777777"
            "nationality": '"
            "ssn": '"
            "birth_place": '"
            "marital_status": '"
            "religion": '"
            "gender": "Male"
            "immigration_status": '"
            "description": '"
            "emp_description": '"
            "emp_type": "581c346d6b0bdc020671e1c2"
            "department": "581c28b16b0bdc02047fcaa3"
            "job_title": "Developer"
            "join_date": '"
            "termination_date": '"
            "birth_date": '"
        }

+ Response 200 (application/json)

    + Body
        {
          "message": "Data updated successfully!!!"
        }


### Get a list of my time sheets [POST /hr/mytimesheets]
Allows the user to get a list of my time sheets that belongs to the Organization/team. 

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
        {
          "payload": [
            {
              "id": "582058166b0bdc17d22a19c2",
              "created_at": "2016-11-07 10:31:50",
              "to": "2016-11-07 10:32:53",
              "from": "2016-11-07 10:31:50",
              "difference": "0.02"
            }
          ]
        }


### Clock-in [POST /hr/clock-in]
Allows the authenticated user to clock in.

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)
    
    + Body
        {
            "message": "Clock-in successful"
        }

+ Response 403 (application/json)
    
    + Body
        {
            "message": "You are not setup as an employee of your organization."
        }

### Clock-out [POST /hr/clock-out]
Allows the authenticated user to clock out if the user is already clocked-in.

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)
    
    + Body
        {
            "message": "Clock-in successful"
        }

+ Response 403 (application/json)
    
    + Body
        {
            "message": "You are not setup as an employee of your organization."
        }


## Sales [/sales]

### Get a list of sales overview [POST /sales/overview]
Allows the user to get a list of sales overview that belongs to the Organization/team. 

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
        {
          "payload": {
            "customer_sales_orders": [
                  {
                    "id": "580ec3528b888048e66070d3",
                    "name": "Elena Gilbert",
                    "items": 2,
                    "value": "1,152,203.63",
                    "status": "Pending",
                    "created": "2016-10-25 02:28:34",
                    "updated": "2016-10-25 02:28:34"
                  } 
              ]
          }
        }


### Get a list of opportunities [POST /sales/opportunities]
Allows the user to get a list of opportunities that belongs to the Organization/team. 

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
       {
          "payload": {
            "opportunities": [
                  {
                    "id": "58006c356b0bdc042c158284",
                    "opportunity": "Wesley & Thadeus & DO ",
                    "customer": "Doe Industries",
                    "contacts": "-",
                    "value": "9,000,000.00",
                    "status": "Decision",
                    "assignee": "",
                    "created_on": "2016-10-14 05:25:07"
                  } 
              ]
          }
        }


### Display opportunity profile [POST /sales/opportunities/opportunity]
Allows the user to display the opportunity according to the given opportunity ID that belongs to the Organization/team. 

+ Parameters
    + opportunityid (string)
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "opportunityid": "582be4976b0bdc0e4f706d82"
        }

+ Response 200 (application/json)

    + Body
       {
          "payload": {
            "0": {
              "id": "58216b4158e13f2bac235f44",
              "customerName": "Demo ABC 08",
              "opportunity": "Demo ABC Opportunity",
              "value": "",
              "status": "New",
              "expectedClose": "2016-11-08",
              "description": "",
              "profileimage": "https://s3.amazonaws.com/fxhellouat/data/102/customer/5821613758e13f2baf56ba22/1478585938-Bm5PoBeomCoc23jZxnh6.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJUVQVA4VO7WZAOVQ%2F20161121%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20161121T101919Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Signature=b4aa5184845f7d950e4cfc4d0354d8ef172b647e95bc2031f906a78889a72ba9",
              "profileImgStatus": true
            },
            "products": []
          }
        }


### Create an opportunity [POST /sales/opportunities/opportunityCreate]
Allows the user to create an opportunity that belongs to the Organization/team. 

+ Parameters
    + customer (string)
    + opportunity (string)
    + category (optional, string)
    + product_categories (optional, string)
    + products (optional, string)
    + contacts (optional, string)
    + value (optional, string)
    + expected_close (optional, string)
    + description (optional, string)
    + status (string)
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "customer": "583285a06b0bdc28804587c2"
            "opportunity": "Demo opportunity"
            "category": ""
            "product_categories": ""
            "products": ""
            "contacts": ""
            "value": "120000"
            "expected_close": "2016-11-21"
            "description": "Demo description"
            "status": "New"
        }

+ Response 200 (application/json)

    + Body
        {
          "message": "Data saved successfully!!!",
          "opportunity_id": "5832cc506b0bdc28804587c4"
        }


### Get vales to the opportunity create form dropdowns [POST /sales/opportunity/dropdowns]
Allows the user to get a list of products, customer & categories that belongs to the Organization/team.

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
       {
          "payload": {
                "products": [
                      {
                        "id": "580083186b0bdc05ff588792",
                        "name": "Mac Book",
                        "price": "2300"
                      }
                  ],
                "customers": [
                      {
                        "id": "57ff51896b0bdc0747634a73",
                        "name": "Francisca Industries PVT LTD"
                      },
                  ],
                "categories": [
                      {
                        "id": "5801b8184189dc69ad4409d9",
                        "name": "GPS"
                      } 
                  ]
          }
        }


### Get the contacts according to the selected customer [POST /sales/opportunities/contacts]
Allows the user to get contacts according to the selected customer that belongs to the Organization/team.

+ Parameters
    + customerid (string) 
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "customerid": "5800a25a6b0bdc06a814c743"
        }


+ Response 200 (application/json)

    + Body
       {
          "payload": {
            "contacts": [
              {
                "id": "5800a2026b0bdc063e70f1a3",
                "contact": "Shelley "
              }
            ]
          }
        }

### Get a list of quotations [POST /sales/quotations]
Allows the user to get a list of quotations that belongs to the Organization/team. 

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
       {
          "payload": [
                {
                  "id": "580084f36b0bdc057904ef12",
                  "name": "Donnie MIllers",
                  "items": 2,
                  "value": "13,375,432.64",
                  "status": "Pending",
                  "updated": "2016-10-14 07:10:41"
                }
            ]
        }


### Display quotation profile [POST /sales/quotations/quotation]
Allows the user to display the quotation according to the given quotation ID that belongs to the Organization/team. 

+ Parameters
    + quotationid (string)
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "quotationid": "581c19816b0bdc032d468a23"
        }

+ Response 200 (application/json)

    + Body
       {
          "payload": {
            "0": {
              "id": "581c19816b0bdc032d468a23",
              "number": "",
              "created_at": "2016-11-04 05:15:45",
              "customername": "Samck Doe",
              "subtotal": "144",
              "discount": "",
              "tax": 19.100736,
              "grand_total": 182.201472,
              "status": "Pending",
              "address1": "",
              "address2": "",
              "city": "",
              "country": "Cook Islands"
            },
            "products": [
              {
                "product_name": "Mac Book",
                "qty": "12",
                "unitprice": "12",
                "discount": "",
                "linetotal": "144"
              }
            ]
          }
        }


### Create quotation [POST /sales/quotations/quotationCreate]
Allows the user to create a quotation that belongs to the Organization/team. 

+ Parameters
    + customer (string)
    + number (optional, string)
    + description (optional, string)
    + orderdate (optional, string)
    + validtill (string)
    + creditperiod (optional, string)
    + product_id (string)
    + qty (string)
    + unitprice (string)
    + discount (string)
    + linetotal (string)
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "customer": "583285a06b0bdc28804587c2"
            "number": "212312"
            "description": ""
            "orderdate": "2016-11-21"
            "validtill": "2016-11-23"
            "creditperiod": "1"
            "product_id": "580083186b0bdc05ff588792"
            "qty": "2"
            "unitprice": "1000"
            "discount": "100"
            "linetotal": "1900"
        }

+ Response 200 (application/json)

    + Body
        {
          "message": "Data saved successfully!!!",
          "quote_id": "5832c7376b0bdc05ce4573b4"
        }


### Get a list of customer sales order [POST /sales/salesorders]
Allows the user to get a list of customer sales that belongs to the Organization/team. 

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
       {
          "payload": {
            "customer_sales_orders": [
                  {
                    "id": "580ec3528b888048e66070d3",
                    "name": "Elena Gilbert",
                    "items": 2,
                    "value": "1,152,203.63",
                    "status": "Pending",
                    "created": "2016-10-25 02:28:34",
                    "updated": "2016-10-25 02:28:34"
                  }
              ],
            "dc_sales_orders": []
          }
        }


### Display sales order profile [POST /sales/salesorders/salesorder]
Allows the user to display the sales order according to the given sales order ID that belongs to the Organization/team. 

+ Parameters
    + salesorder_id (string)
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "salesorder_id": "582be4976b0bdc0e4f706d82"
        }

+ Response 200 (application/json)

    + Body
       {
          "payload": {
            "0": {
              "id": "582be4976b0bdc0e4f706d82",
              "number": "5345",
              "created_at": "2016-11-16 04:46:14",
              "customername": "Cass Industries",
              "subtotal": 4500000,
              "discount": 0,
              "tax": 596898,
              "grand_total": 5693796,
              "status": "Pending",
              "address1": "2131",
              "address2": "Galle Road",
              "city": "Colombo",
              "country": "Bolivia"
            },
            "products": [
              {
                "product_name": "Books",
                "qty": "45",
                "unitprice": "100000.00",
                "discount": "0.00",
                "linetotal": "4500000.00"
              }
            ]
          }
        }


### Create sales order [POST /sales/salesorders/salesorderCreate]
Allows the user to create a sales order that belongs to the Organization/team. 

+ Parameters
    + customer (string)
    + quotenumber (optional, string)
    + sonumber (optional, string)
    + description (optional, string)
    + orderdate (string)
    + creditperiod (optional, string)
    + product_id (string)
    + qty (string)
    + unitprice (string)
    + discount (string)
    + linetotal (string)
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "customer": "583285a06b0bdc28804587c2"
            "quotenumber": "212312"
            "sonumber": "213123"
            "description": ""
            "orderdate": "2016-11-21"
            "creditperiod": "1"
            "product_id": "580083186b0bdc05ff588792"
            "qty": "2"
            "unitprice": "1000"
            "discount": "100"
            "linetotal": "1900"
        }

+ Response 200 (application/json)

    + Body
        {
          "message": "Data saved successfully!!!",
          "sales_order_id": "5832c4af6b0bdc05cd7f9e32"
        }


### Get a list of invoices [POST /sales/invoices]
Allows the user to get a list of invoices that belongs to the Organization/team. 

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
       {
          "payload": [
                {
                  "id": "58008b4a6b0bdc06881cfab2",
                  "name": "Donnie MIllers",
                  "items": 1,
                  "value": "8,857,276.08",
                  "status": "Pending",
                  "created": "2016-10-14 07:37:46",
                  "updated": "2016-10-14 07:37:46"
                }
            ]
        }


### Display invoice profile [POST /sales/invoices/invoice]
Allows the user to display the invoice according to the given invoice ID that belongs to the Organization/team. 

+ Parameters
    + invoiceid (string)
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "invoiceid": "582be4976b0bdc0e4f706d82"
        }

+ Response 200 (application/json)

    + Body
       {
          "payload": {
            "0": {
              "id": "582036996b0bdc14b145f4f2",
              "number": null,
              "created_at": "2016-11-07 08:08:57",
              "customername": "Samck Doe",
              "subtotal": "144",
              "discount": null,
              "tax": 19.100736,
              "grand_total": 182.201472,
              "status": "Pending",
              "address1": "",
              "address2": "",
              "city": "",
              "country": "Cook Islands"
            },
            "products": [
              {
                "product_name": "Mac Book",
                "qty": "12",
                "unitprice": "12",
                "discount": "",
                "linetotal": "144"
              }
            ]
          }
        }


### Create an invoice [POST /sales/invoices/invoiceCreate]
Allows the user to create an invoice that belongs to the Organization/team. 

+ Parameters
    + customer (string)
    + quotenumber (optional, string)
    + sonumber (optional, string)
    + description (optional, string)
    + orderdate (string)
    + creditperiod (optional, string)
    + product_id (string)
    + qty (string)
    + unitprice (string)
    + discount (string)
    + linetotal (string)
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "customer": "583285a06b0bdc28804587c2"
            "quotenumber": "212312"
            "sonumber": "213123"
            "description": ""
            "orderdate": "2016-11-21"
            "creditperiod": "1"
            "product_id": "580083186b0bdc05ff588792"
            "qty": "2"
            "unitprice": "1000"
            "discount": "100"
            "linetotal": "1900"
        }

+ Response 200 (application/json)

    + Body
        {
          "message": "Data saved successfully!!!",
          "invoice_id": "5832c8e56b0bdc05ce4573b5"
        }


### Get a list of workorders [POST /sales/workorders]
Allows the user to get a list of work orders that belongs to the Organization/team. 

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
       {
          "payload": [
                {
                  "id": "57ff36816b0bdc06f947f0f2",
                  "appointment": "2016-10-26",
                  "name": "Clive workorder",
                  "customer_name": "Clive Industries",
                  "status": 1
                }
            ]
        }


### Get values to the dropdowns in quotation, sales order and invoice create forms [POST /sales/products/dropdowns]
Allows the user to get values to the dropdowns in quotation, sales order and invoice create forms that belongs to the Organization/team.
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
      {
          "payload": {
            "products": [
                  {
                    "id": "580083186b0bdc05ff588792",
                    "name": "Mac Book",
                    "price": "2300"
                  } 
              ],
            "customers": [
                  {
                    "id": "57ff51896b0bdc0747634a73",
                    "name": "Francisca Industries PVT LTD"
                  }, 
              ]
          }
        }


### Get the product price [POST /sales/products/product/price]
Allows the user to get the product price that belongs to the Organization/team.

+ Parameters
    + productid (string) 
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "productid": "580083186b0bdc05ff588792"
        }


+ Response 200 (application/json)

    + Body
      {
          "payload": [
            {
              "id": "580083186b0bdc05ff588792",
              "price": "2300"
            }
          ]
        }


## Marketing [/marketing]

### Get a list of marketing campaigns [POST /marketing/campaigns]
Allows the user to get a list of marketing campaigns that belongs to the Organization/team. 

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
      {
          "payload": [
                {
                  "id": "580494806b0bdc02f42265a2",
                  "campaign": "New marketing campaign"
                } 
            ]
        }


### Create a marketing campaign [POST /marketing/campaigns/campaignCreate]
Allows the user to create a marketing campaign that belongs to the Organization/team. 

+ Parameters
    + category (string)
    + campaign (string)
    + location (optional, string)
    + assign_to (optional, string)
    + description (optional, string)
    + budget_allocation (optional, string)
    + start_date (optional, string)
    + end_date (optional, string)
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "category": "5801b8184189dc69ad4409ea"
            "campaign": "Demo campaign"
            "location": "New York"
            "assign_to": ""
            "description": "Demo"
            "budget_allocation": "12000"
            "start_date": "2016-09-26"
            "end_date": "2016-11-26"
        }

+ Response 200 (application/json)

    + Body
       {
          "message": "Data saved successfully!!!"
        }


### Get a list of marketing resources [POST /marketing/resources]
Allows the user to get a list of marketing resources that belongs to the Organization/team. 

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
      {
          "payload": [
                {
                  "id": "58049c806b0bdc0212189813",
                  "resource": "New marketing 123",
                  "location": "New York",
                  "zone": "",
                  "category": "580493816b0bdc0530310c32",
                  "user": "",
                  "date": "2016-10-17 09:40:15"
                }
            ]
        }


### Display marketing resource profile [POST /marketing/resources/resource]
Allows the user to get details of the marketing resource that belongs to the Organization/team. 

+ Parameters
    + resourceid (string) 
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "resourceid": "58219ae758e13f3933622853"
        }

+ Response 200 (application/json)

    + Body
        {
          "payload": [
            {
              "id": "58219ae758e13f3933622853",
              "name": "Demo M Resource 08",
              "categoryName": "first resource category",
              "location": "New York",
              "profileimage": "https://cdn.fxhello.com/img/imgph300.png",
              "profileImgStatus": false,
              "cuid": 1679,
              "uuid": 1679,
              "created_at": "2016-11-08 09:29:11",
              "updated_at": "2016-11-08 09:29:11"
            }
          ]
        }


### Create a marketing resource [POST /marketing/resources/resourceCreate]
Allows the user to create a marketing resource that belongs to the Organization/team. 

+ Parameters
    + category (string)
    + resource (string)
    + location (optional, string)
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "category": "5801b8184189dc69ad4409f8"
            "resource": "Demo marketing resource"
            "location": "New York"
        }

+ Response 200 (application/json)

    + Body
       {
          "message": "Data saved successfully!!!",
          "resource_id": "5832d9c26b0bdc070f6b9702"
        }


## Products [/products]

### Get a list of products [POST /products/products]
Allows the user to get a list of products that belongs to the Organization/team. 

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
      {
        "payload": [
            {
              "id": "580083186b0bdc05ff588792",
              "sku": "FX000000",
              "product_name": "Mac Book",
              "price": "2300",
              "categoryName": "Laptop",
              "created_at": "2016-11-08 02:40:49",
              "updated_at": "2016-11-08 02:40:49"
            } 
          ]
      }


### Get a list of weight units [POST /products/products/weight-units]
Allows the user to get a list of weight units that belongs to the Organization/team. 

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
      {
        "payload": [
          {
            "id": 9,
            "symbol": "g"
          },
          {
            "id": 10,
            "symbol": "Kg"
          },
          {
            "id": 11,
            "symbol": "t"
          }
        ]
      }


### Get a list of length units [POST /products/products/length-units]
Allows the user to get a list of length units that belongs to the Organization/team. 

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
     {
        "payload": [
          {
            "id": 2,
            "symbol": "cm"
          },
          {
            "id": 6,
            "symbol": "ft"
          },
          {
            "id": 5,
            "symbol": "in"
          },
          {
            "id": 4,
            "symbol": "Km"
          },
          {
            "id": 3,
            "symbol": "m"
          },
          {
            "id": 8,
            "symbol": "mi"
          },
          {
            "id": 1,
            "symbol": "mm"
          },
          {
            "id": 7,
            "symbol": "yd"
          }
        ]
      }

## Finance [/finances]

### Get a list of finance invoices [POST /finances/invoices]
Allows the user to get a list of finance invoices that belongs to the Organization/team. 

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
     {
        "payload": {
          "invoices": [
            {
              "id": "58008b4a6b0bdc06881cfab2",
              "name": "Donnie MIllers",
              "items": 1,
              "value": "8,857,276.08",
              "status": "Pending",
              "created": "2016-10-14 07:37:46",
              "updated": "2016-10-14 07:37:46"
            }
          ]
        }
      }


### Get a list of finance sales orders [POST /finances/salesorders]
Allows the user to get a list of finance sales orders that belongs to the Organization/team. 

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
     {
        "payload": {
          "customer_sales_orders": [
            {
              "id": "580ec3528b888048e66070d3",
              "name": "Elena Gilbert",
              "items": 2,
              "value": "1,152,203.63",
              "status": "Pending",
              "created": "2016-10-25 02:28:34",
              "updated": "2016-10-25 02:28:34"
            }
          ],
          "dc_sales_orders": []
        }
      }


## Sales force [/salesforce]

### Get a list of sales force resources [POST /salesforce/resources]
Allows the user to get a list of sales force resources that belongs to the Organization/team. 

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
     {
        "payload": {
          "resources": [
            {
              "id": "5805e3ac6b0bdc09d366df82",
              "name": "Nickles Domnick",
              "performance": "",
              "goal": ""
            },
            {
              "id": "581b02cf58e13f5b131505d2",
              "name": "Erwines Genel",
              "performance": "",
              "goal": ""
            }
          ]
        }
      }


### Get a list of sales force tasks [POST /salesforce/tasks]
Allows the user to get a list of sales force tasks that belongs to the Organization/team. 

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
    {
      "payload": [
        {
          "id": "5821a4506b0bdc02f8023fc2",
          "title": "First task"
        }
      ]
    }

## General [/]

### Get a list of countries [POST /countries]
Allows the user to get a list of countries that belongs to the Organization/team. 

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
     {
        "countries": [
          {
            "id": 232,
            "country": "United States"
          }
        ]
      }

### Health-check pings [POST /health-check-pings]
Saves the data of the health-check pings on in to the database

+ Parameters
    + gpsOn (boolean) ... TRUE if GPS is on, FALSE if off and NULL if not available
    + gpsLat (decimal) ... GPS Latitude
    + gpsLon (decimal) ... GPS Longitude

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            'gpsOn': true,
            'gpsLat': 12.12545,
            'gpsLon': 64.12487,
            'gpsSignalStrength': '12dB',
            'batteryPercentage': 87,
            'dataOn': true,
            'dataStrength': '',
            'gsmOn': true,
            'gsmStrength': '',
            'timestamp': '2016-11-23 16:23:52'
        }

+ Response 200 (application/json)
    + Body
        {
          "message": "Data save successful."
        }
