FORMAT: 1A
HOST: http://uat.fxhello.com/api/

# FX Hello

Polls is a simple API allowing consumers to view polls and vote in them.

IMPORTANT: The API URL is set to UAT server in this documentation. Make sure to change the URL to http://app.fxhello.com to communicate with the Production system.

## Authentication [/authenticate]

### Login [POST]
Allows the user to login using their email address and the password. The API will return a JSON Web Token (JWT) upon successful login. This token needs to be sent in the header of each call of the API.

+ Request

    + Headers
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "email": "user@example.com",
            "password": "Abc@1234"
        }
    
+ Response 200 (application/json)

    + Body
        {
            "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1",
            "isError": false
        }

### Register [POST /register]
Allows user to create an account

+ Request (application/json)

    + Headers
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "name": "John",
            "email": "john@example.com",
            "password": "Abc@1234",
            "password_confirmation": "Abc@1234"
        }

+ Response 200 (application/json)

    + Body
        {
            "user": {
                "name": "TOne",
                "email": "tone@flatorb.com",
                "updated_at": "2016-11-21 05:56:03",
                "created_at": "2016-11-21 05:56:03",
                "id": 1640,
                "tax_rate": 0
            }
            "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1",
            "isError": false
        }
        
## Categories [/categories]

### Get a list of categories [POST /categories]
Allows the user to get a list of categories and their ID's that belongs to the Organization/team. 

+ Parameters
    + subType (optional, number) ... NULL or 0 return all categories. Passing the relavent subType return only the applicable categories.
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "subType": 0
        }

+ Response 200 (application/json)

    + Body
        {
           "payload": {
             "customers": [
                {
                    "id": "57fdc2c06b0bdc7ee01a59d2",
                    "name": "New Customer category"
                }
             ],
            "contacts": [
                {
                    "id": "57fdc2006b0bdc7d6809b522",
                    "name": "New contact category"
                }
            ]
            },
            "code": 200
         }
        

### Create category [POST /categories/save]
This allows the user to create a new contact category.

+ Parameters
    + subType (optional, number) ...  subType = 3 for customers and subType = 4 for contacts. Can keep it as NULL or 0.


+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "name": "The new contact category name"
            "subType": 3
        }

+ Response 201 (application/json)

    + Body
        {
              "message": "Data saved successfully!!!",
              "code": 200
        }

## Background services [/services]


## Stores [/stores]

### Get list of stores [POST /stores]
Get a list of stores (warehouses, store locations, etc.) along with their ID, type.

+ Parameters
    + subType (optional, number) ... NULL or 0 return all stores. Passing the relavent subType return only the applicable stores from the store type.
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "subType": 0
        }

+ Response 200 (application/json)

    + Body
        {
            "payload" : ""
        }

## CRM [/crm]

### Get a list of customers [POST /crm/customers]
Allows the user to get a list of customers and their information that belongs to the Organization/team. 
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
        {
           "payload": [
                {
                  "id": "57ff51896b0bdc0747634a73",
                  "name": "Francisca Industries PVT LTD",
                  "status": "Prospect",
                  "email": "fransis@flatorb.com",
                  "telephone": "675677 , 234",
                  "added_by": "Keshani",
                  "profileimage": "https://cdn.fxhello.com/img/imgph300.png",
                  "profileImgStatus": false,
                  "created_on": "2016-10-13 09:19:03"
                 }
            ],
            "code": 200
        }

### Get a list of categories [POST /categories]
Allows the user to get a list of categories and their ID's that belongs to the Organization/team. 

+ Parameters
    + subType (optional, number) ... NULL or 0 return all categories. Passing the relavent subType return only the applicable categories.
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "subType": 0
        }

+ Response 200 (application/json)

    + Body
        {
           "payload": {
             "customers": [
                {
                    "id": "57fdc2c06b0bdc7ee01a59d2",
                    "name": "New Customer category"
                }
             ],
            "contacts": [
                {
                    "id": "57fdc2006b0bdc7d6809b522",
                    "name": "New contact category"
                }
            ]
            },
            "code": 200
         }


## Support [/support]

## HR [/hr]

### Clock-in [POST /hr/clock-in]
Allows the authenticated user to clock in.

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)
    
    + Body
        {
            "message": "Clock-in successful"
        }

+ Response 403 (application/json)
    
    + Body
        {
            "message": "You are not setup as an employee of your organization."
        }

### Clock-out [POST /hr/clock-out]
Allows the authenticated user to clock out if the user is already clocked-in.

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)
    
    + Body
        {
            "message": "Clock-in successful"
        }

+ Response 403 (application/json)
    
    + Body
        {
            "message": "You are not setup as an employee of your organization."
        }