FORMAT: 1A
HOST: http://uat.fxhello.com/api/

# FX Hello

Polls is a simple API allowing consumers to view polls and vote in them.

IMPORTANT: The API URL is set to UAT server in this documentation. Make sure to change the URL to http://app.fxhello.com to communicate with the Production system.

## Authentication [/authenticate]

### Login [POST]
Allows the user to login using their email address and the password. The API will return a JSON Web Token (JWT) upon successful login. This token needs to be sent in the header of each call of the API.

+ Request

    + Headers
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "email": "user@example.com",
            "password": "Abc@1234"
        }
    
+ Response 200 (application/json)

    + Body
        {
            "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1",
            "isError": false
        }

### Register [POST /register]
Allows user to create an account

+ Request (application/json)

    + Headers
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "name": "John",
            "email": "john@example.com",
            "password": "Abc@1234",
            "password_confirmation": "Abc@1234"
        }

+ Response 200 (application/json)

    + Body
        {
            "user": {
                "name": "TOne",
                "email": "tone@flatorb.com",
                "updated_at": "2016-11-21 05:56:03",
                "created_at": "2016-11-21 05:56:03",
                "id": 1640,
                "tax_rate": 0
            }
            "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1",
            "isError": false
        }
        
## Categories [/categories]

### Get a list of categories [POST /categories]
Allows the user to get a list of categories and their ID's that belongs to the Organization/team. 

+ Parameters
    + subType (optional, number) ... NULL or 0 return all categories. Passing the relavent subType return only the applicable categories.
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "subType": 0
        }

+ Response 200 (application/json)

    + Body
        {
           "payload": {
             "customers": [
                {
                    "id": "57fdc2c06b0bdc7ee01a59d2",
                    "name": "New Customer category"
                }
             ],
            "contacts": [
                {
                    "id": "57fdc2006b0bdc7d6809b522",
                    "name": "New contact category"
                }
            ]
            },
            "code": 200
         }
        

### Create category [POST /categories/save]
This allows the user to create a new category.

+ Parameters
    + subType (optional, number) ...  subType = 3 for customers and subType = 4 for contacts. Can keep it as NULL or 0.


+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "name": "The new contact category name"
            "subType": 3
        }

+ Response 201 (application/json)

    + Body
        {
              "message": "Data saved successfully!!!",
              "code": 200
        }

## Background services [/services]


## Stores [/stores]

### Get list of stores [POST /stores]
Get a list of stores (warehouses, store locations, etc.) along with their ID, type.

+ Parameters
    + subType (optional, number) ... NULL or 0 return all stores. Passing the relavent subType return only the applicable stores from the store type.
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "subType": 0
        }

+ Response 200 (application/json)

    + Body
        {
            "payload" : ""
        }

## CRM [/crm]

### Get a list of customers [POST /crm/customers]
Allows the user to get a list of customers and their information that belongs to the Organization/team. 
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
        {
           "payload": [
                {
                  "id": "57ff51896b0bdc0747634a73",
                  "name": "Francisca Industries PVT LTD",
                  "status": "Prospect",
                  "email": "fransis@flatorb.com",
                  "telephone": "675677 , 234",
                  "added_by": "Keshani",
                  "profileimage": "https://cdn.fxhello.com/img/imgph300.png",
                  "profileImgStatus": false,
                  "created_on": "2016-10-13 09:19:03"
                 }
            ],
            "code": 200
        }

### Display customer profile [POST /crm/customers/customer]
Allows the user to get customer details of the selected customer that belongs to the Organization/team. 

+ Parameters
    + customerid (string) ... Passing the relavent customerId to return only the relevant customer details.
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "customerid": 5806d9fe6b0bdc0209217585
        }

+ Response 200 (application/json)

    + Body
        {
          "payload": [
            {
              "id": "5806d9fe6b0bdc0209217585",
              "name": "Aileen Annie",
              "addresses": {
                "address1": "",
                "address2": "",
                "city": "",
                "state": "",
                "stateid": null,
                "zip": "",
                "country": "Estonia",
                "countryid": "64",
                "description": "",
                "status": 1,
                "cuid": 6,
                "uuid": 6,
                "created_at": "2016-10-19 02:27:07",
                "updated_at": "2016-10-19 02:27:07"
              },
              "telephone1": "",
              "telephone2": null,
              "mobile": "",
              "fax": null,
              "status": "Prospect",
              "email": "",
              "website": "",
              "description": "",
              "profileimage": "https://cdn.fxhello.com/img/imgph300.png",
              "profileImgStatus": false,
              "leadSource": "Lead",
              "customerSince": "2016-10-19",
              "creditPeriod": null,
              "cuName": "Keshani",
              "created_at": "2016-10-19 02:27:07",
              "uuName": "Keshani",
              "updated_at": "2016-10-19 02:27:07"
            }
          ]
    }


### Create a customer [POST /crm/customers/customer/save]
Allows the user to  saves a customer under the active Organization/team. 

+ Parameters
    + name (string) 
    + prefix (string)
    + category (optional, string)
    + email (optional, string)
    + website (optional, string)
    + country (number)
    + address1 (optional, string)
    + address2 (optional, string)
    + city (optional, string)
    + zip (optional, string)
    + state (optional, string)
    + telephone1 (optional, string)
    + telephone2 (optional, string)
    + mobile (string)
    + fax (optional, string)
    + status (string)
    + leadsource (string)
    + customer_since (optional, string)
    + description (optional, string)
    + designation (optional, string)
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "name": "Github test customer"
            "prefix": "Mr.""
            "category": "5801b8184189dc69ad4409e7"
            "email": "git@flatorb.com"
            "website": "www.github.com"
            "country": 23
            "address1": "123"
            "address2": "Galle Road"
            "city": "Colombo"
            "zip": "0"
            "state": "0"
            "telephone1": "011 11111111"
            "telephone2": "022 22222222"
            "mobile": "077 7777777"
            "fax": "011 1111111"
            "status": '3"
            "leadsource": "581ab6a058e13f4536380912"
            "customer_since": "2016-11-13"
            "description": "Test Customer"
            "designation": "Developer"
        }

+ Response 200 (application/json)

    + Body
        {
          "message": "Data saved successfully!!!",
          "code": 200,
          "customer_id": "583285a06b0bdc28804587c2"
        }


### Edit customer [POST /crm/customers/customer/edit]
Allows the user to get customer details of the selected customer to the edit form, that belongs to the Organization/team. 

+ Parameters
    + customerid (string) ... Passing the relavent customerId to return only the relevant customer details.
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "customerid": "583285a06b0bdc28804587c2"
        }

+ Response 200 (application/json)

    + Body
        {
          "payload": [
            {
              "id": "583285a06b0bdc28804587c2",
              "name": "Github test customer",
              "addresses": {
                "address1": "123",
                "address2": "Colombo Road",
                "city": "Colombo",
                "state": "",
                "stateid": "",
                "zip": "",
                "country": "Bahrain",
                "countryid": "Bahrain",
                "description": "",
                "status": 1,
                "cuid": 1679,
                "uuid": 1679,
                "created_at": "2016-11-21 05:26:51",
                "updated_at": "2016-11-21 05:26:51"
              },
              "telephone1": "45345",
              "telephone2": "435345",
              "mobile": "34534",
              "fax": "345345",
              "statusID": "3",
              "status": "Lead",
              "email": "git@flatorb.com",
              "website": "",
              "description": "",
              "countryID": "Bahrain",
              "leadSourceID": "581ab6a058e13f4536380912",
              "leadSource": "Mailed",
              "customerSince": "1970-01-01",
              "cuName": "Keshani",
              "created_at": "2016-11-21 05:26:51",
              "uuName": "Keshani",
              "updated_at": "2016-11-21 05:26:51"
            }
          ]
    }


### Update customer [POST /crm/customers/customer/update]
Allows the user to  update the selected customer under the active Organization/team. 

+ Parameters
    + customerid (string) 
    + name (string) 
    + prefix (string)
    + category (optional, string)
    + email (optional, string)
    + website (optional, string)
    + country (number)
    + address1 (optional, string)
    + address2 (optional, string)
    + city (optional, string)
    + zip (optional, string)
    + state (optional, string)
    + telephone1 (optional, string)
    + telephone2 (optional, string)
    + mobile (string)
    + fax (optional, string)
    + status (string)
    + leadsource (string)
    + customer_since (optional, string)
    + description (optional, string)
    + designation (optional, string)
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "customerid": "583285a06b0bdc28804587c2"
            "name": "Github demo customer "
            "prefix": "Mr.""
            "category": "5801b8184189dc69ad4409e7"
            "email": "git@flatorb.com"
            "website": "www.github.com"
            "country": 23
            "address1": "123"
            "address2": "Galle Road"
            "city": "Colombo"
            "zip": "0"
            "state": "0"
            "telephone1": "011 11111111"
            "telephone2": "022 22222222"
            "mobile": "077 7777777"
            "fax": "011 1111111"
            "status": '3"
            "leadsource": "581ab6a058e13f4536380912"
            "customer_since": "2016-11-13"
            "description": "Test Customer"
            "designation": "Developer"
        }

+ Response 200 (application/json)

    + Body
        {
          "message": "Data updated successfully!!!",
          "code": 200
        }


### Get a list of contacts [POST /crm/contacts]
Allows the user to get a list of contacts and their information that belongs to the Organization/team. 
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
        {
           "payload": [
                {
                    "id": "57ff61a96b0bdc091d013592",
                    "name": "Genevieve Isabelle",
                    "company": null,
                    "position": "HR",
                    "telephone": "344234 , 234234",
                    "email": "gene@flatorb.com",
                    "added_by": "Keshani",
                    "profileimage": "https://cdn.fxhello.com/img/imgph300.png",
                    "profileImgStatus": false,
                    "created_on": "2016-10-13 10:27:52"
                }
            ],
            "code": 200
        }


### Display contact profile [POST /crm/contacts/contact]
Allows the user to get contact details of the selected contact that belongs to the Organization/team. 

+ Parameters
    + contactid (string) ... Passing the relavent contactId to return only the relevant contact details.
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "contactid": 5806d9fe6b0bdc0209217585
        }

+ Response 200 (application/json)

    + Body
        {
          "payload": [
            {
              "id": "57ff61a96b0bdc091d013592",
              "customerName": null,
              "firstName": "Genevieve",
              "lastName": "Isabelle",
              "telephone": "344234",
              "mobile": "234234",
              "email": "gene@flatorb.com",
              "image": "",
              "position": "HR",
              "profileimage": "https://cdn.fxhello.com/img/imgph300.png",
              "profileImgStatus": false,
              "addresses": {
                "address1": "234",
                "address2": "Galle Road",
                "city": "Colombo",
                "state": "",
                "stateid": null,
                "zip": "",
                "country": "Ecuador",
                "countryid": "63",
                "description": "",
                "status": 1,
                "cuid": 6,
                "uuid": 6,
                "created_at": "2016-10-13 10:27:52",
                "updated_at": "2016-10-13 10:27:52"
              }
            }
        ]
    }


### Create a Contact [POST /crm/contacts/contact/save]
Allows the user to  saves a contact under the active Organization/team. 

+ Parameters
    + customer (optional, string) 
    + prefix (string)
    + firstName (string)
    + middleName (optional, string)
    + lastName (optional, string)
    + email (optional, string)
    + country (number)
    + position (optional, string)
    + department (optional, string)
    + contact_type (optional, string)
    + telephone (optional, string)
    + mobile (string)
    + address1 (optional, string)
    + address2 (optional, string)
    + city (optional, string)
    + post_code (string)
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "customer": "583285a06b0bdc28804587c2"
            "prefix": "Mr.""
            "firstName": "Git"
            "middleName": "Contact"
            "lastName": "Demo"
            "email": "git@flatorb.com"
            "country": "56"
            "position": "Trainee Developer"
            "department": "IT"
            "contact_type": ""
            "telephone": "011 1111111"
            "mobile": "077 7777777"
            "address1": "45"
            "address2": "Galle Road"
            "city": "Colombo"
            "post_code": '"
        }

+ Response 200 (application/json)

    + Body
    {
        "message": "Data saved successfully!!!",
        "code": 200,
        "contact_id": "58329bf16b0bdc244f367da3"
    }


### Edit contact [POST /crm/contacts/contact/edit]
Allows the user to get contact details of the selected contact to the edit form, that belongs to the Organization/team. 

+ Parameters
    + contactid (string) ... Passing the relavent contactId to return only the relevant contact details.
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "contactid": "58329bf16b0bdc244f367da3"
        }

+ Response 200 (application/json)

    + Body
        {
          "payload": [
            {
              "id": "58329bf16b0bdc244f367da3",
              "cutomerName": "Github demo customer ",
              "firstName": "Git",
              "middleName": "Contact",
              "lastName": "Demo",
              "telephone": "011 1111111",
              "mobile": "077 7777777",
              "email": "git@flatorb.com",
              "title": "Trainee Developer",
              "image": "",
              "department": "IT",
              "contact_type": "",
              "addresses": {
                "address1": "45",
                "address2": "Galle Road",
                "city": "Colombo",
                "state": "",
                "zip": "",
                "country": "Czech Republic",
                "countryid": "Czech Republic",
                "description": "",
                "status": 1,
                "cuid": 1679,
                "uuid": 1679,
                "created_at": "2016-11-21 07:02:07",
                "updated_at": "2016-11-21 07:02:07"
              }
            }
          ]
        }


### Update contact [POST /crm/contacts/contact/update]
Allows the user to  update the selected contact under the active Organization/team. 

+ Parameters
    + contactid (string) 
    + prefix (string) 
    + firstName (string)
    + middleName (optional, string)
    + lastName (optional, string)
    + email (optional, string)
    + country (number)
    + position (optional, string)
    + department (optional, string)
    + contact_type (optional, string)
    + telephone (optional, string)
    + mobile (string)
    + address1 (optional, string)
    + address2 (optional, string)
    + city (optional, string)
    + post_code (optional, string)
    
+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json
    + Body
        {
            "contactid": "583285a06b0bdc28804587c2"
            "prefix": "Github demo customer "
            "firstName": "Mr.""
            "middleName": "5801b8184189dc69ad4409e7"
            "lastName": "git@flatorb.com"
            "email": "www.github.com"
            "country": 23
            "position": "123"
            "department": "Galle Road"
            "contact_type": "Colombo"
            "telephone": "0"
            "mobile": "0"
            "address1": "011 11111111"
            "address2": "022 22222222"
            "city": "077 7777777"
            "post_code": "011 1111111"
        }

+ Response 200 (application/json)

    + Body
        {
          "message": "Data updated successfully!!!",
          "code": 200
        }


### Get values for the customer create from dropdowns [POST /crm/customer/dropdowns]
Allows the user to get a list of values for the drop downs countries, customer status and lead source that belongs to the Organization/team. 

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
        {
          "payload": {
                "countries": [
                  {
                    "id": 3,
                    "country": "Afghanistan"
                  }
                ],
                "customerStatuses": [
                  {
                    "id": 1,
                    "status": "Customer"
                  },
                ],
                "leadSources": [
                  {
                    "id": "57fcd93e4189dc6a846be182",
                    "source": "This is test"
                  },
                ],
                "categories": [
                 {
                    "id": "57fdc2c06b0bdc7ee01a59d2",
                    "name": "New Customer category"
                  },
                ]
            },
            "code": 200
        }


### Get values for the contact create from dropdowns [POST /crm/contact/dropdowns]
Allows the user to get a list of values for the drop downs countries and customers that belongs to the Organization/team. 

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)

    + Body
        {
          "payload": {
                "countries": [
                  {
                    "id": 3,
                    "country": "Afghanistan"
                  }
                ],
                "customers": [
                  {
                    "id": "57ff51896b0bdc0747634a73",
                    "name": "Francisca Industries PVT LTD"
                  },
                ]
            },
            "code": 200
        }


## Support [/support]

## HR [/hr]

### Clock-in [POST /hr/clock-in]
Allows the authenticated user to clock in.

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)
    
    + Body
        {
            "message": "Clock-in successful"
        }

+ Response 403 (application/json)
    
    + Body
        {
            "message": "You are not setup as an employee of your organization."
        }

### Clock-out [POST /hr/clock-out]
Allows the authenticated user to clock out if the user is already clocked-in.

+ Request

    + Headers
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ
            Accept: application/vnd.fxhello.v1+json

+ Response 200 (application/json)
    
    + Body
        {
            "message": "Clock-in successful"
        }

+ Response 403 (application/json)
    
    + Body
        {
            "message": "You are not setup as an employee of your organization."
        }